name: Dump
on: push
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dump
        id: dump
        with:
          enable-context: 'true'
      - run: |
          echo "${DATE}"
          echo "${{ steps.dump }}"
          echo "${{ steps.dump.outputs }}"
          echo "${{ steps.dump.outputs.dumped-date }}"
        env:
          DATE: ${{ steps.dump.outputs.dumped-date }}
